use MiniFacebook
go

---Non-repeatable reads

--T1
BEGIN TRAN
WAITFOR DELAY '00:00:05'
UPDATE Categories SET categoryDescription='DESCRIPTION NONREPEATABLE READS' WHERE categoryID = 2
COMMIT TRAN

--T2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Categories
WAITFOR DELAY '00:00:05'
SELECT * FROM Categories
COMMIT TRAN


--Solution 


--T1
BEGIN TRAN
WAITFOR DELAY '00:00:05'
UPDATE Categories SET
categoryDescription='DESCRIPTION NON REPEATABLEREADS' WHERE categoryID = 2
COMMIT TRAN


--T2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Categories
WAITFOR DELAY '00:00:05'
SELECT * FROM Categories
COMMIT TRAN
