ALTER DATABASE GradesDatabase SET ALLOW_SNAPSHOT_ISOLATION ON

use GradesDatabase
go

WAITFOR DELAY '00:00:10'
BEGIN TRAN
UPDATE Grade
SET val = 4
WHERE courseID = 4

WAITFOR DELAY '00:00:10'
COMMIT TRAN


SELECT * FROM Course
SELECT * FROM Grade