USE GradesDatabase
GO


---Dirty reads
BEGIN TRANSACTION
UPDATE Students
SET studentName = 'Mihai'
WHERE studentID = 5
WAITFOR DELAY '00:00:10'
ROLLBACK TRANSACTION

--- NON-REPEATABLE READS
INSERT INTO Students(studentName, cnp) VALUES ('VALE', 133564)
BEGIN TRANSACTION
WAITFOR DELAY '00:00:10'
UPDATE Students
SET cnp = 1
WHERE studentID = (SELECT IDENT_CURRENT('Student'))
COMMIT TRANSACTION


--- PHANTOM READS
BEGIN TRANSACTION
WAITFOR DELAY '00:00:10'
INSERT INTO Course(courseName, val) VALUES ('SDA', 7)
COMMIT TRANSACTION


--- DEADLOCK
BEGIN TRANSACTION
UPDATE Course SET courseName='newName1' WHERE courseID=2
WAITFOR DELAY '00:00:10'
UPDATE Course SET courseName='newName2' WHERE courseID=3
COMMIT TRAN


SET DEADLOCK_PRIORITY LOW
BEGIN TRANSACTION
UPDATE Course SET courseName='newName1' WHERE courseID=2
WAITFOR DELAY '00:00:10'
UPDATE Course SET courseName='newName2' WHERE courseID=3
COMMIT TRAN

SELECT * FROM Students
SELECT * FROM Grade
SELECT * FROM Course
