use GradesDatabase
go

SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
SELECT * FROM Grade WHERE gradeID = 1
WAITFOR DELAY '00:00:10'
UPDATE Grade
SET val = 1
WHERE gradeID = 1

COMMIT TRAN


SELECT * FROM Grades